-- 상품 데이터 생성 스크립트
-- CSV 파일들을 임시 테이블로 넣고 크로스 조인해서 상품 테이블에 데이터 생성
-- 생성 시간: 2025-08-11T17:29:56.142Z

-- 1. 임시 테이블 생성
CREATE TEMPORARY TABLE temp_determiner (
    id INT AUTO_INCREMENT PRIMARY KEY,
    determiner VARCHAR(100) NOT NULL
);

CREATE TEMPORARY TABLE temp_item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item VARCHAR(100) NOT NULL
);

CREATE TEMPORARY TABLE temp_brand (
    id INT AUTO_INCREMENT PRIMARY KEY,
    brand_name VARCHAR(500) NOT NULL
);

-- 2. CSV 데이터 삽입

-- 관형사 데이터 삽입 (총 900개)
INSERT INTO temp_determiner (determiner) VALUES
('하얀 바다의'),
('붉은 금의'),
('전설의 숲의'),
('얼어붙은 독의'),
('화려한 폭풍의'),
('강철의 마법의'),
('신성한 불의'),
('전설의 늑대의'),
('은밀한 은의'),
('신성한 은의'),
('하얀 철의'),
('강철의 바다의'),
('영원의 별빛의'),
('화려한 늑대의'),
('어둠의 영혼의'),
('거대한 산의'),
('반짝이는 호랑이의'),
('희귀한 바다의'),
('강철의 별빛의'),
('푸른 평원의'),
('광기의 바다의'),
('지혜로운 태양의'),
('검은 불의'),
('은밀한 그림자의'),
('은밀한 하늘의'),
('날렵한 번개의'),
('은빛 은의'),
('하얀 달빛의'),
('용맹한 빛의'),
('빛나는 달빛의'),
('검은 평원의'),
('영원의 바다의'),
('희귀한 불꽃의'),
('가시 돋친 금의'),
('지혜로운 마법의'),
('강철의 철의'),
('푸른 불의'),
('검은 호랑이의'),
('날렵한 물의'),
('영원의 그림자의'),
('하얀 번개의'),
('하얀 불꽃의'),
('반짝이는 용의'),
('얼어붙은 물의'),
('거대한 피의'),
('위대한 서리의'),
('반짝이는 별빛의'),
('빛바랜 바람의'),
('하얀 호랑이의'),
('전설의 심연의'),
('지혜로운 숲의'),
('희귀한 피의'),
('은빛 사자의'),
('광기의 숲의'),
('용맹한 그림자의'),
('빛나는 산의'),
('광기의 하늘의'),
('신비한 서리의'),
('희귀한 용의'),
('가시 돋친 은의'),
('용맹한 별빛의'),
('푸른 사자의'),
('빛바랜 철의'),
('푸른 달빛의'),
('하얀 평원의'),
('광기의 불꽃의'),
('빛바랜 달빛의'),
('검은 사자의'),
('화려한 호랑이의'),
('화려한 번개의'),
('날렵한 철의'),
('황금빛 빛의'),
('불타는 은의'),
('반짝이는 영혼의'),
('빛바랜 사자의'),
('붉은 심연의'),
('붉은 철의'),
('신성한 그림자의'),
('지혜로운 철의'),
('강철의 불의'),
('빛나는 번개의'),
('하얀 폭풍의'),
('영원의 은의'),
('거대한 달빛의'),
('빛나는 하늘의'),
('거대한 숲의'),
('은밀한 사자의'),
('빛바랜 서리의'),
('은빛 바람의'),
('태고의 그림자의'),
('신비한 호랑이의'),
('용맹한 용의'),
('신비한 불의'),
('얼어붙은 태양의'),
('신비한 산의'),
('거대한 하늘의'),
('얼어붙은 바람의'),
('하얀 마법의'),
('희귀한 늑대의'),
('서리내린 철의'),
('서리내린 그림자의'),
('저주받은 독의'),
('광기의 금의'),
('희귀한 금의'),
('날렵한 금의'),
('검은 용의'),
('은빛 독의'),
('은빛 번개의'),
('태고의 물의'),
('푸른 그림자의'),
('날렵한 용의'),
('서리내린 늑대의'),
('광기의 평원의'),
('서리내린 하늘의'),
('저주받은 산의'),
('검은 늑대의'),
('붉은 늑대의'),
('태고의 서리의'),
('은빛 영혼의'),
('은빛 빛의'),
('황금빛 사자의'),
('신성한 별빛의'),
('위대한 금의'),
('영원의 불꽃의'),
('가시 돋친 별빛의'),
('용맹한 불꽃의'),
('은밀한 물의'),
('빛나는 사자의'),
('저주받은 철의'),
('은밀한 불꽃의'),
('가시 돋친 바다의'),
('거대한 번개의'),
('저주받은 폭풍의'),
('신비한 숲의'),
('빛나는 별빛의'),
('영원의 마법의'),
('태고의 영혼의'),
('푸른 산의'),
('신비한 은의'),
('얼어붙은 호랑이의'),
('희귀한 호랑이의'),
('날렵한 바람의'),
('불타는 번개의'),
('황금빛 폭풍의'),
('위대한 용의'),
('빛나는 빛의'),
('얼어붙은 사자의'),
('용맹한 마법의'),
('강철의 숲의'),
('용맹한 평원의'),
('얼어붙은 땅의'),
('희귀한 영혼의'),
('은빛 불꽃의'),
('반짝이는 태양의'),
('용맹한 바다의'),
('태고의 호랑이의'),
('검은 서리의'),
('반짝이는 숲의'),
('푸른 독의'),
('은빛 태양의'),
('광기의 그림자의'),
('지혜로운 은의'),
('반짝이는 산의'),
('날렵한 심연의'),
('황금빛 서리의'),
('은빛 숲의'),
('어둠의 달빛의'),
('거대한 바다의'),
('황금빛 불꽃의'),
('영원의 빛의'),
('붉은 별빛의'),
('빛바랜 불꽃의'),
('서리내린 서리의'),
('전설의 태양의'),
('태고의 평원의'),
('강철의 금의'),
('용맹한 독의'),
('영원의 독의'),
('태고의 빛의'),
('신성한 피의'),
('강철의 산의'),
('검은 금의'),
('반짝이는 빛의'),
('강철의 바람의'),
('신비한 심연의'),
('반짝이는 불꽃의'),
('황금빛 평원의'),
('용맹한 번개의'),
('얼어붙은 하늘의'),
('용맹한 은의'),
('불타는 영혼의'),
('영원의 땅의'),
('빛바랜 바다의'),
('지혜로운 그림자의'),
('불타는 서리의'),
('지혜로운 금의'),
('영원의 폭풍의'),
('거대한 금의'),
('영원의 번개의'),
('지혜로운 폭풍의'),
('희귀한 마법의'),
('반짝이는 심연의'),
('빛나는 태양의'),
('하얀 사자의'),
('전설의 불꽃의'),
('빛나는 피의'),
('광기의 바람의'),
('전설의 산의'),
('신비한 독의'),
('신비한 영혼의'),
('반짝이는 평원의'),
('신비한 태양의'),
('희귀한 빛의'),
('반짝이는 하늘의'),
('강철의 그림자의'),
('희귀한 은의'),
('가시 돋친 독의'),
('빛바랜 불의'),
('신비한 땅의'),
('빛바랜 마법의'),
('저주받은 그림자의'),
('붉은 불의'),
('얼어붙은 피의'),
('은밀한 마법의'),
('신비한 번개의'),
('지혜로운 산의'),
('어둠의 은의'),
('날렵한 늑대의'),
('화려한 용의'),
('빛나는 금의'),
('검은 독의'),
('황금빛 피의'),
('영원의 용의'),
('빛바랜 땅의'),
('화려한 피의'),
('푸른 별빛의'),
('하얀 태양의'),
('광기의 별빛의'),
('빛나는 숲의'),
('어둠의 태양의'),
('화려한 불꽃의'),
('푸른 호랑이의'),
('거대한 불꽃의'),
('태고의 늑대의'),
('얼어붙은 바다의'),
('서리내린 물의'),
('얼어붙은 폭풍의'),
('영원의 철의'),
('용맹한 물의'),
('위대한 철의'),
('태고의 독의'),
('태고의 폭풍의'),
('하얀 산의'),
('얼어붙은 달빛의'),
('불타는 폭풍의'),
('영원의 늑대의'),
('거대한 사자의'),
('화려한 마법의'),
('은빛 산의'),
('황금빛 숲의'),
('전설의 하늘의'),
('붉은 은의'),
('은밀한 평원의'),
('강철의 피의'),
('황금빛 별빛의'),
('어둠의 철의'),
('불타는 금의'),
('영원의 달빛의'),
('날렵한 바다의'),
('날렵한 빛의'),
('은빛 서리의'),
('붉은 호랑이의'),
('저주받은 달빛의'),
('희귀한 번개의'),
('어둠의 금의'),
('푸른 숲의'),
('태고의 철의'),
('하얀 은의'),
('불타는 마법의'),
('서리내린 마법의'),
('신성한 서리의'),
('신성한 바람의'),
('불타는 산의'),
('하얀 독의'),
('날렵한 달빛의'),
('불타는 독의'),
('빛나는 폭풍의'),
('용맹한 서리의'),
('위대한 폭풍의'),
('붉은 바다의'),
('위대한 숲의'),
('영원의 사자의'),
('전설의 피의'),
('빛바랜 그림자의'),
('얼어붙은 번개의'),
('희귀한 불의'),
('빛바랜 늑대의'),
('가시 돋친 물의'),
('빛나는 독의'),
('은빛 폭풍의'),
('강철의 심연의'),
('얼어붙은 심연의'),
('불타는 사자의'),
('광기의 번개의'),
('저주받은 태양의'),
('하얀 심연의'),
('푸른 불꽃의'),
('거대한 폭풍의'),
('용맹한 태양의'),
('붉은 숲의'),
('태고의 은의'),
('위대한 영혼의'),
('신성한 땅의'),
('서리내린 산의'),
('전설의 독의'),
('얼어붙은 평원의'),
('거대한 은의'),
('은밀한 철의'),
('광기의 땅의'),
('가시 돋친 불꽃의'),
('서리내린 땅의'),
('은빛 심연의'),
('은밀한 독의'),
('어둠의 번개의'),
('위대한 평원의'),
('푸른 바람의'),
('강철의 늑대의'),
('하얀 물의'),
('저주받은 불의'),
('용맹한 철의'),
('황금빛 태양의'),
('반짝이는 은의'),
('태고의 바람의'),
('태고의 별빛의'),
('강철의 땅의'),
('가시 돋친 불의'),
('검은 불꽃의'),
('은밀한 폭풍의'),
('서리내린 평원의'),
('붉은 그림자의'),
('푸른 은의'),
('빛나는 바다의'),
('하얀 땅의'),
('저주받은 번개의'),
('붉은 마법의'),
('날렵한 불꽃의'),
('황금빛 영혼의'),
('신성한 사자의'),
('은밀한 용의'),
('서리내린 바람의'),
('빛바랜 금의'),
('신성한 호랑이의'),
('신비한 달빛의'),
('광기의 피의'),
('황금빛 심연의'),
('빛바랜 번개의'),
('신성한 빛의'),
('은빛 철의'),
('위대한 심연의'),
('서리내린 불의'),
('태고의 마법의'),
('위대한 그림자의'),
('거대한 마법의'),
('강철의 불꽃의'),
('은밀한 달빛의'),
('강철의 용의'),
('영원의 물의'),
('저주받은 물의'),
('황금빛 바람의'),
('전설의 빛의'),
('빛나는 바람의'),
('위대한 피의'),
('지혜로운 영혼의'),
('빛나는 물의'),
('전설의 물의'),
('황금빛 마법의'),
('은빛 늑대의'),
('용맹한 피의'),
('신성한 산의'),
('태고의 달빛의'),
('신비한 용의'),
('지혜로운 번개의'),
('은밀한 땅의'),
('화려한 사자의'),
('서리내린 영혼의'),
('강철의 평원의'),
('빛나는 용의'),
('광기의 사자의'),
('서리내린 심연의'),
('붉은 달빛의'),
('광기의 산의'),
('희귀한 폭풍의'),
('저주받은 영혼의'),
('반짝이는 사자의'),
('하얀 서리의'),
('하얀 별빛의'),
('용맹한 영혼의'),
('지혜로운 용의'),
('지혜로운 평원의'),
('거대한 평원의'),
('저주받은 호랑이의'),
('검은 빛의'),
('서리내린 빛의'),
('불타는 평원의'),
('저주받은 하늘의'),
('지혜로운 바람의'),
('가시 돋친 마법의'),
('위대한 바람의'),
('빛바랜 호랑이의'),
('영원의 서리의'),
('황금빛 바다의'),
('가시 돋친 그림자의'),
('전설의 용의'),
('황금빛 그림자의'),
('황금빛 하늘의'),
('거대한 태양의'),
('신비한 그림자의'),
('용맹한 달빛의'),
('반짝이는 금의'),
('신비한 바다의'),
('검은 태양의'),
('은밀한 바다의'),
('용맹한 산의'),
('강철의 태양의'),
('강철의 서리의'),
('저주받은 평원의'),
('빛나는 불꽃의'),
('빛바랜 빛의'),
('서리내린 용의'),
('태고의 하늘의'),
('희귀한 태양의'),
('신성한 금의'),
('서리내린 별빛의'),
('푸른 태양의'),
('거대한 불의'),
('지혜로운 바다의'),
('강철의 호랑이의'),
('저주받은 피의'),
('반짝이는 마법의'),
('반짝이는 번개의'),
('신비한 철의'),
('강철의 하늘의'),
('붉은 서리의'),
('검은 마법의'),
('희귀한 산의'),
('불타는 하늘의'),
('가시 돋친 태양의'),
('붉은 태양의'),
('가시 돋친 산의'),
('광기의 태양의'),
('빛바랜 별빛의'),
('전설의 영혼의'),
('붉은 피의'),
('은밀한 빛의'),
('전설의 불의'),
('날렵한 서리의'),
('위대한 땅의'),
('검은 바람의'),
('황금빛 은의'),
('푸른 물의'),
('위대한 하늘의'),
('전설의 평원의'),
('빛나는 은의'),
('신비한 평원의'),
('희귀한 하늘의'),
('영원의 피의'),
('불타는 물의'),
('서리내린 달빛의'),
('화려한 바람의'),
('신성한 늑대의'),
('태고의 땅의'),
('전설의 마법의'),
('위대한 마법의'),
('서리내린 은의'),
('검은 하늘의'),
('날렵한 태양의'),
('위대한 달빛의'),
('얼어붙은 용의'),
('신비한 마법의'),
('어둠의 바람의'),
('얼어붙은 산의'),
('불타는 피의'),
('불타는 늑대의'),
('신성한 독의'),
('화려한 물의'),
('신성한 용의'),
('전설의 땅의'),
('지혜로운 달빛의'),
('은밀한 별빛의'),
('날렵한 폭풍의'),
('검은 번개의'),
('위대한 빛의'),
('저주받은 늑대의'),
('검은 땅의'),
('푸른 번개의'),
('광기의 물의'),
('용맹한 불의'),
('불타는 바다의'),
('빛바랜 독의'),
('지혜로운 빛의'),
('신비한 사자의'),
('전설의 번개의'),
('지혜로운 서리의'),
('푸른 영혼의'),
('은빛 평원의'),
('가시 돋친 사자의'),
('은빛 금의'),
('불타는 불의'),
('위대한 불꽃의'),
('영원의 숲의'),
('황금빛 금의'),
('얼어붙은 철의'),
('강철의 달빛의'),
('지혜로운 피의'),
('불타는 그림자의'),
('저주받은 마법의'),
('어둠의 숲의'),
('어둠의 하늘의'),
('지혜로운 사자의'),
('희귀한 심연의'),
('불타는 바람의'),
('검은 심연의'),
('푸른 철의'),
('은밀한 서리의'),
('신비한 불꽃의'),
('빛나는 불의'),
('신성한 태양의'),
('얼어붙은 빛의'),
('하얀 늑대의'),
('광기의 늑대의'),
('전설의 서리의'),
('희귀한 서리의'),
('얼어붙은 영혼의'),
('희귀한 바람의'),
('화려한 금의'),
('어둠의 산의'),
('은빛 호랑이의'),
('어둠의 바다의'),
('푸른 마법의'),
('은빛 피의'),
('지혜로운 하늘의'),
('용맹한 하늘의'),
('어둠의 서리의'),
('붉은 하늘의'),
('전설의 달빛의'),
('신성한 마법의'),
('날렵한 은의'),
('화려한 달빛의'),
('신비한 물의'),
('지혜로운 독의'),
('저주받은 빛의'),
('붉은 불꽃의'),
('희귀한 별빛의'),
('강철의 은의'),
('신성한 철의'),
('저주받은 용의'),
('어둠의 늑대의'),
('태고의 태양의'),
('화려한 철의'),
('반짝이는 달빛의'),
('신비한 바람의'),
('저주받은 사자의'),
('위대한 사자의'),
('붉은 용의'),
('어둠의 그림자의'),
('날렵한 피의'),
('화려한 바다의'),
('반짝이는 바람의'),
('황금빛 철의'),
('하얀 그림자의'),
('하얀 불의'),
('어둠의 용의'),
('반짝이는 그림자의'),
('반짝이는 폭풍의'),
('빛나는 땅의'),
('빛나는 늑대의'),
('빛바랜 심연의'),
('희귀한 독의'),
('강철의 영혼의'),
('어둠의 독의'),
('푸른 빛의'),
('얼어붙은 마법의'),
('은밀한 늑대의'),
('용맹한 땅의'),
('불타는 땅의'),
('가시 돋친 호랑이의'),
('어둠의 호랑이의'),
('붉은 번개의'),
('전설의 바람의'),
('은밀한 심연의'),
('황금빛 달빛의'),
('얼어붙은 늑대의'),
('불타는 별빛의'),
('은빛 바다의'),
('위대한 번개의'),
('황금빛 독의'),
('은밀한 산의'),
('붉은 사자의'),
('푸른 심연의'),
('저주받은 바람의'),
('강철의 물의'),
('은밀한 불의'),
('은밀한 태양의'),
('은빛 물의'),
('어둠의 빛의'),
('화려한 그림자의'),
('어둠의 심연의'),
('거대한 호랑이의'),
('푸른 하늘의'),
('거대한 철의'),
('거대한 심연의'),
('반짝이는 피의'),
('푸른 땅의'),
('신성한 폭풍의'),
('검은 바다의'),
('황금빛 용의'),
('불타는 빛의'),
('광기의 독의'),
('빛바랜 폭풍의'),
('은밀한 금의'),
('광기의 달빛의'),
('신성한 심연의'),
('저주받은 땅의'),
('서리내린 금의'),
('하얀 용의'),
('빛바랜 피의'),
('얼어붙은 금의'),
('빛바랜 물의'),
('거대한 땅의'),
('전설의 폭풍의'),
('위대한 호랑이의'),
('가시 돋친 바람의'),
('푸른 폭풍의'),
('화려한 태양의'),
('화려한 하늘의'),
('얼어붙은 불의'),
('용맹한 숲의'),
('지혜로운 불의'),
('가시 돋친 늑대의'),
('영원의 바람의'),
('신성한 번개의'),
('용맹한 사자의'),
('불타는 숲의'),
('황금빛 산의'),
('서리내린 숲의'),
('신성한 평원의'),
('가시 돋친 폭풍의'),
('화려한 숲의'),
('희귀한 달빛의'),
('붉은 땅의'),
('태고의 불꽃의'),
('푸른 금의'),
('태고의 피의'),
('빛바랜 용의'),
('화려한 은의'),
('전설의 은의'),
('황금빛 늑대의'),
('광기의 심연의'),
('붉은 바람의'),
('붉은 물의'),
('반짝이는 바다의'),
('은빛 땅의'),
('신성한 바다의'),
('반짝이는 철의'),
('저주받은 숲의'),
('날렵한 마법의'),
('어둠의 마법의'),
('검은 폭풍의'),
('빛바랜 영혼의'),
('푸른 용의'),
('반짝이는 늑대의'),
('광기의 폭풍의'),
('위대한 늑대의'),
('거대한 용의'),
('빛나는 영혼의'),
('어둠의 평원의'),
('날렵한 사자의'),
('은빛 불의'),
('얼어붙은 은의'),
('희귀한 물의'),
('은빛 하늘의'),
('가시 돋친 번개의'),
('신성한 달빛의'),
('가시 돋친 땅의'),
('하얀 금의'),
('희귀한 그림자의'),
('용맹한 심연의'),
('저주받은 서리의'),
('영원의 평원의'),
('날렵한 불의'),
('위대한 은의'),
('가시 돋친 피의'),
('은빛 마법의'),
('은밀한 숲의'),
('은밀한 피의'),
('검은 산의'),
('검은 달빛의'),
('날렵한 호랑이의'),
('어둠의 별빛의'),
('화려한 서리의'),
('태고의 심연의'),
('위대한 태양의'),
('광기의 영혼의'),
('가시 돋친 용의'),
('거대한 별빛의'),
('태고의 금의'),
('반짝이는 물의'),
('화려한 별빛의'),
('서리내린 태양의'),
('은밀한 바람의'),
('가시 돋친 하늘의'),
('위대한 별빛의'),
('가시 돋친 평원의'),
('서리내린 호랑이의'),
('영원의 산의'),
('빛나는 철의'),
('빛바랜 산의'),
('푸른 서리의'),
('가시 돋친 서리의'),
('광기의 빛의'),
('태고의 사자의'),
('은빛 달빛의'),
('태고의 용의'),
('검은 별빛의'),
('황금빛 땅의'),
('푸른 피의'),
('얼어붙은 그림자의'),
('빛바랜 태양의'),
('황금빛 물의'),
('은밀한 호랑이의'),
('광기의 호랑이의'),
('신비한 늑대의'),
('어둠의 사자의'),
('강철의 폭풍의'),
('지혜로운 늑대의'),
('날렵한 땅의'),
('희귀한 땅의'),
('화려한 영혼의'),
('하얀 빛의'),
('태고의 바다의'),
('신성한 물의'),
('어둠의 불의'),
('푸른 바다의'),
('붉은 빛의'),
('하얀 피의'),
('저주받은 바다의'),
('저주받은 불꽃의'),
('서리내린 사자의'),
('푸른 늑대의'),
('용맹한 금의'),
('검은 철의'),
('영원의 심연의'),
('서리내린 폭풍의'),
('빛바랜 숲의'),
('불타는 호랑이의'),
('하얀 숲의'),
('거대한 물의'),
('불타는 달빛의'),
('불타는 불꽃의'),
('가시 돋친 달빛의'),
('전설의 사자의'),
('은빛 그림자의'),
('지혜로운 호랑이의'),
('강철의 번개의'),
('광기의 은의'),
('붉은 영혼의'),
('날렵한 평원의'),
('날렵한 영혼의'),
('위대한 물의'),
('태고의 숲의'),
('반짝이는 땅의'),
('반짝이는 서리의'),
('지혜로운 별빛의'),
('어둠의 땅의'),
('황금빛 번개의'),
('용맹한 폭풍의'),
('강철의 독의'),
('하얀 하늘의'),
('희귀한 평원의'),
('빛나는 서리의'),
('검은 영혼의'),
('붉은 산의'),
('서리내린 독의'),
('신비한 피의'),
('저주받은 심연의'),
('영원의 하늘의'),
('가시 돋친 심연의'),
('서리내린 불꽃의'),
('어둠의 불꽃의'),
('가시 돋친 빛의'),
('은밀한 번개의'),
('위대한 산의'),
('전설의 그림자의'),
('광기의 마법의'),
('거대한 영혼의'),
('신성한 숲의'),
('은빛 별빛의'),
('얼어붙은 서리의'),
('거대한 바람의'),
('화려한 심연의'),
('얼어붙은 불꽃의'),
('저주받은 은의'),
('희귀한 사자의'),
('날렵한 하늘의'),
('지혜로운 불꽃의'),
('불타는 철의'),
('위대한 바다의'),
('광기의 서리의'),
('광기의 철의'),
('희귀한 철의'),
('전설의 철의'),
('지혜로운 심연의'),
('거대한 빛의'),
('서리내린 바다의'),
('반짝이는 불의'),
('신성한 하늘의'),
('광기의 불의'),
('영원의 불의'),
('거대한 그림자의'),
('황금빛 호랑이의'),
('어둠의 폭풍의'),
('전설의 호랑이의'),
('빛나는 평원의'),
('검은 피의'),
('날렵한 숲의'),
('불타는 용의'),
('불타는 심연의'),
('가시 돋친 철의'),
('붉은 평원의'),
('화려한 독의'),
('검은 그림자의'),
('화려한 땅의'),
('날렵한 그림자의'),
('위대한 불의'),
('붉은 폭풍의'),
('광기의 용의'),
('서리내린 피의'),
('지혜로운 물의'),
('어둠의 피의'),
('위대한 독의'),
('빛나는 호랑이의'),
('붉은 독의'),
('은밀한 영혼의'),
('얼어붙은 숲의'),
('전설의 금의'),
('신비한 별빛의'),
('강철의 빛의'),
('영원의 태양의'),
('빛나는 그림자의'),
('반짝이는 독의'),
('가시 돋친 영혼의'),
('빛바랜 하늘의'),
('신비한 빛의'),
('빛바랜 평원의'),
('서리내린 번개의'),
('하얀 바람의'),
('지혜로운 땅의'),
('신비한 하늘의'),
('저주받은 금의'),
('빛바랜 은의'),
('검은 숲의'),
('황금빛 불의'),
('신비한 금의'),
('희귀한 숲의'),
('영원의 영혼의'),
('태고의 불의'),
('신비한 폭풍의'),
('거대한 늑대의'),
('불타는 태양의'),
('신성한 불꽃의'),
('전설의 별빛의'),
('화려한 평원의'),
('화려한 불의'),
('검은 은의'),
('화려한 산의'),
('은빛 용의'),
('강철의 사자의'),
('용맹한 호랑이의'),
('하얀 영혼의'),
('전설의 바다의'),
('저주받은 별빛의'),
('검은 물의'),
('태고의 번개의'),
('거대한 서리의'),
('어둠의 물의'),
('영원의 금의'),
('거대한 독의'),
('영원의 호랑이의'),
('날렵한 별빛의'),
('날렵한 독의'),
('화려한 빛의'),
('가시 돋친 숲의'),
('빛나는 심연의'),
('빛나는 마법의'),
('태고의 산의'),
('용맹한 바람의'),
('신성한 영혼의'),
('용맹한 늑대의'),
('날렵한 산의'),
('얼어붙은 별빛의');

-- 아이템 데이터 삽입 (총 1000개)
INSERT INTO temp_item (item) VALUES
('지팡이혼'),
('상고리결정'),
('활대송곳니'),
('철문영혼'),
('망치갑옷'),
('철창영혼'),
('활대투구'),
('갑옷조각'),
('갑옷투구'),
('보물상자'),
('활대갑옷'),
('은괴문양'),
('석상망토'),
('메달비늘'),
('해골혼'),
('메달혼'),
('깃발반지'),
('서적핵'),
('보석목걸이'),
('방패비늘'),
('말발굽검'),
('철문파편'),
('열쇠돌'),
('깃털망토'),
('단지장갑'),
('방울조각'),
('수정구날개'),
('수리검갑옷'),
('석판문양'),
('열쇠투구'),
('돌조각갑옷'),
('궤짝핵'),
('버클혼'),
('단검혼'),
('팔찌핵'),
('철퇴혼'),
('단검돌'),
('단검날개'),
('나침반비늘'),
('부츠투구'),
('반지검'),
('비단핵'),
('비단혼'),
('석궁비늘'),
('쇠구슬비늘'),
('포탄결정'),
('갑주투구'),
('방패판'),
('성배날개'),
('지도검'),
('사슬비늘'),
('포탄돌'),
('금괴송곳니'),
('고리송곳니'),
('열쇠혼'),
('단검비늘'),
('보물상자검'),
('갑주파편'),
('돌기둥부츠'),
('송곳니부츠'),
('칼날송곳니'),
('지도송곳니'),
('지도장갑'),
('항아리목걸이'),
('왕관방패'),
('활송곳니'),
('투척검파편'),
('목걸이창'),
('갑주돌'),
('은괴발톱'),
('보물상자투구'),
('지팡이심장'),
('나침반돌'),
('상고리망토'),
('허리띠파편'),
('쇠사슬부츠'),
('석궁장갑'),
('수정구투구'),
('활장갑'),
('검비늘'),
('석상발톱'),
('석상조각'),
('철창부츠'),
('보물상자송곳니'),
('훈장'),
('은괴영혼'),
('창날반지'),
('가면핵'),
('창날개'),
('포탄'),
('옷감갑옷'),
('쇠구슬'),
('메달투구'),
('상자결정'),
('포탄심장'),
('돌기둥핵'),
('상고리혼'),
('나침반'),
('뼈문양'),
('가면부츠'),
('갑옷영혼'),
('모자장갑'),
('날개'),
('방패갑옷'),
('날개목걸이'),
('칼날조각'),
('말발굽부츠'),
('철창돌'),
('돌기둥갑옷'),
('왕관반지'),
('투척검망토'),
('열쇠파편'),
('보물상자창'),
('말발굽결정'),
('고리'),
('용비늘문양'),
('램프혼'),
('장갑장갑'),
('금괴돌'),
('철창투구'),
('방패'),
('방패판부츠'),
('방울망토'),
('해골문양'),
('궤짝방패'),
('탄환검'),
('사슬핵'),
('망토창'),
('날개핵'),
('해골영혼'),
('철퇴돌'),
('서적돌'),
('철편검'),
('훈장심장'),
('단검망토'),
('성배혼'),
('방울방패'),
('쇠사슬투구'),
('송곳니심장'),
('창투구'),
('반지돌'),
('모자조각'),
('망토검'),
('귀걸이영혼'),
('철퇴반지'),
('투구투구'),
('돌기둥날개'),
('장갑부츠'),
('화살비늘'),
('탄환창'),
('궤짝발톱'),
('방울파편'),
('창날투구'),
('장갑조각'),
('동전결정'),
('나침반핵'),
('상고리장갑'),
('피리반지'),
('깃털핵'),
('룬영혼'),
('나침반파편'),
('보석갑옷'),
('비단부츠'),
('말발굽창'),
('장갑파편'),
('철문결정'),
('금괴문양'),
('조각상장갑'),
('마법서돌'),
('조각상파편'),
('투척검방패'),
('반지문양'),
('가면조각'),
('허리띠송곳니'),
('석궁'),
('방패발톱'),
('금괴심장'),
('망치영혼'),
('비단망토'),
('피리방패'),
('망토돌'),
('서적혼'),
('고리창'),
('수리검장갑'),
('철창결정'),
('철퇴심장'),
('비단영혼'),
('단검투구'),
('탄환송곳니'),
('금괴창'),
('쇠사슬결정'),
('은괴'),
('검장갑'),
('발톱핵'),
('뿔창'),
('궤짝날개'),
('투구돌'),
('돌조각날개'),
('방탄복결정'),
('용비늘장갑'),
('철편방패'),
('항아리'),
('수정구조각'),
('포탄혼'),
('망토방패'),
('금괴핵'),
('마법서장갑'),
('수정구혼'),
('병혼'),
('송곳니날개'),
('가면문양'),
('돌기둥망토'),
('창살망토'),
('성배투구'),
('방울'),
('활대목걸이'),
('가면혼'),
('열쇠결정'),
('창날심장'),
('수리검송곳니'),
('팔찌돌'),
('철편비늘'),
('금괴혼'),
('금괴결정'),
('말발굽영혼'),
('조각상심장'),
('귀걸이혼'),
('깃발핵'),
('활돌'),
('활결정'),
('탄환망토'),
('갑옷핵'),
('말발굽송곳니'),
('허리띠갑옷'),
('화살망토'),
('철문투구'),
('날개영혼'),
('목걸이투구'),
('포탄조각'),
('램프갑옷'),
('돌기둥검'),
('목걸이영혼'),
('뿔망토'),
('나침반투구'),
('투구창'),
('창살투구'),
('석상'),
('부츠'),
('검돌'),
('보물상자망토'),
('사슬심장'),
('룬부츠'),
('투척검장갑'),
('망토부츠'),
('발톱망토'),
('날개날개'),
('갑옷갑옷'),
('궤짝갑옷'),
('철문송곳니'),
('보물상자파편'),
('고리검'),
('방탄복목걸이'),
('열쇠반지'),
('반지심장'),
('귀걸이핵'),
('용비늘파편'),
('날개망토'),
('병망토'),
('방울혼'),
('투척검혼'),
('옷감영혼'),
('항아리부츠'),
('돌기둥결정'),
('투구검'),
('금괴영혼'),
('램프송곳니'),
('고리방패'),
('열쇠문양'),
('목걸이심장'),
('석궁영혼'),
('보물상자날개'),
('깃털조각'),
('보석송곳니'),
('나침반갑옷'),
('열쇠핵'),
('활검'),
('방패판발톱'),
('용비늘날개'),
('갑주창'),
('철문창'),
('사슬방패'),
('반지날개'),
('해골핵'),
('철편결정'),
('금괴망토'),
('깃발방패'),
('지팡이투구'),
('메달핵'),
('쇠사슬장갑'),
('은괴결정'),
('망토심장'),
('고리핵'),
('망토장갑'),
('포탄문양'),
('서적갑옷'),
('수정구송곳니'),
('날개심장'),
('열쇠심장'),
('말발굽혼'),
('서적비늘'),
('석판송곳니'),
('수리검결정'),
('단검문양'),
('상자날개'),
('갑옷'),
('비단검'),
('모자방패'),
('귀걸이목걸이'),
('쇠구슬영혼'),
('마법서심장'),
('성배핵'),
('비단창'),
('수정구갑옷'),
('상자부츠'),
('성배문양'),
('반지파편'),
('보물상자부츠'),
('상고리'),
('창부츠'),
('지도발톱'),
('쇠사슬검'),
('팔찌'),
('돌조각반지'),
('용비늘'),
('궤짝비늘'),
('뿔돌'),
('귀걸이비늘'),
('갑주방패'),
('활대장갑'),
('동전망토'),
('포탄부츠'),
('화살조각'),
('창날망토'),
('병투구'),
('방탄복검'),
('허리띠검'),
('창살심장'),
('병발톱'),
('모자망토'),
('발톱부츠'),
('창날장갑'),
('사슬발톱'),
('석상창'),
('해골갑옷'),
('뿔발톱'),
('장갑방패'),
('깃발창'),
('모자반지'),
('궤짝투구'),
('단지조각'),
('단검심장'),
('투구장갑'),
('옷감창'),
('머리띠부츠'),
('탄환목걸이'),
('방울돌'),
('돌조각비늘'),
('철퇴핵'),
('훈장송곳니'),
('룬창'),
('지도핵'),
('가면방패'),
('조각상문양'),
('방울발톱'),
('장갑갑옷'),
('말발굽투구'),
('상자갑옷'),
('나침반날개'),
('창날혼'),
('갑옷장갑'),
('목걸이파편'),
('왕관갑옷'),
('팔찌조각'),
('왕관결정'),
('지도영혼'),
('조각상핵'),
('마법서망토'),
('방울검'),
('투구반지'),
('갑주갑옷'),
('룬장갑'),
('마법서날개'),
('마법서부츠'),
('방패날개'),
('석판혼'),
('망토송곳니'),
('수리검문양'),
('깃발결정'),
('팔찌목걸이'),
('조각상창'),
('갑옷비늘'),
('돌조각망토'),
('팔찌심장'),
('병부츠'),
('화살날개'),
('고리문양'),
('날개부츠'),
('방탄복투구'),
('철퇴목걸이'),
('철편파편'),
('방탄복돌'),
('방패송곳니'),
('철퇴갑옷'),
('허리띠부츠'),
('허리띠반지'),
('성배돌'),
('마법서투구'),
('망치심장'),
('철문돌'),
('옷감투구'),
('동전방패'),
('은괴장갑'),
('방탄복송곳니'),
('버클장갑'),
('망토비늘'),
('궤짝목걸이'),
('방패판돌'),
('병창'),
('상자검'),
('방탄복방패'),
('단검발톱'),
('허리띠날개'),
('귀걸이'),
('깃털반지'),
('창날목걸이'),
('방패판혼'),
('발톱반지'),
('철편심장'),
('투척검영혼'),
('훈장발톱'),
('보석심장'),
('버클문양'),
('훈장방패'),
('목걸이핵'),
('상자투구'),
('반지결정'),
('상자돌'),
('동전문양'),
('목걸이갑옷'),
('망치'),
('지도반지'),
('부츠비늘'),
('석판방패'),
('용비늘검'),
('피리핵'),
('쇠구슬장갑'),
('돌조각결정'),
('훈장창'),
('깃발검'),
('항아리반지'),
('피리검'),
('장갑돌'),
('메달갑옷'),
('칼날목걸이'),
('머리띠비늘'),
('지팡이송곳니'),
('부츠심장'),
('방패핵'),
('지팡이목걸이'),
('송곳니결정'),
('보물상자갑옷'),
('탄환조각'),
('뿔'),
('피리영혼'),
('쇠사슬돌'),
('발톱영혼'),
('사슬반지'),
('갑옷망토'),
('보석날개'),
('칼날문양'),
('팔찌문양'),
('망치목걸이'),
('칼날망토'),
('석판망토'),
('지팡이날개'),
('창살혼'),
('항아리장갑'),
('열쇠갑옷'),
('피리날개'),
('뼈영혼'),
('상자문양'),
('서적장갑'),
('모자검'),
('탄환방패'),
('돌기둥돌'),
('인장갑옷'),
('목걸이발톱'),
('해골결정'),
('지도돌'),
('말발굽파편'),
('상자비늘'),
('궤짝부츠'),
('갑주송곳니'),
('비단반지'),
('메달결정'),
('비단목걸이'),
('송곳니방패'),
('장갑핵'),
('용비늘결정'),
('철편장갑'),
('모자창'),
('깃털장갑'),
('궤짝파편'),
('투척검조각'),
('철퇴검'),
('지도혼'),
('깃발갑옷'),
('보물상자영혼'),
('망치조각'),
('활혼'),
('해골반지'),
('창살핵'),
('방울부츠'),
('해골'),
('가면날개'),
('고리혼'),
('말발굽반지'),
('방패판목걸이'),
('뿔날개'),
('마법서결정'),
('돌기둥조각'),
('방패검'),
('지팡이방패'),
('투구갑옷'),
('버클갑옷'),
('방패판파편'),
('쇠구슬날개'),
('돌기둥파편'),
('창영혼'),
('창살문양'),
('칼날파편'),
('탄환발톱'),
('보석혼'),
('동전조각'),
('뿔갑옷'),
('병검'),
('방탄복혼'),
('방울반지'),
('갑옷부츠'),
('피리창'),
('머리띠투구'),
('갑주장갑'),
('화살갑옷'),
('조각상영혼'),
('활대날개'),
('갑옷파편'),
('검'),
('동전돌'),
('뼈비늘'),
('상자창'),
('지팡이망토'),
('피리문양'),
('지팡이조각'),
('방탄복비늘'),
('날개발톱'),
('팔찌부츠'),
('검날개'),
('철창송곳니'),
('보물상자방패'),
('망토갑옷'),
('귀걸이창'),
('옷감심장'),
('단지부츠'),
('가면반지'),
('철문망토'),
('석판심장'),
('병문양'),
('석상결정'),
('옷감비늘'),
('뼈돌'),
('깃털목걸이'),
('용비늘비늘'),
('활대부츠'),
('램프발톱'),
('갑옷목걸이'),
('단지'),
('피리송곳니'),
('갑주날개'),
('부츠목걸이'),
('나침반발톱'),
('날개방패'),
('단검창'),
('방패판방패'),
('깃발발톱'),
('갑옷방패'),
('창날파편'),
('룬'),
('석상비늘'),
('버클날개'),
('활영혼'),
('깃발문양'),
('보물상자장갑'),
('마법서조각'),
('지도망토'),
('왕관'),
('보석발톱'),
('해골조각'),
('단검방패'),
('깃털결정'),
('보석문양'),
('지도파편'),
('장갑'),
('지도목걸이'),
('해골방패'),
('귀걸이결정'),
('갑옷창'),
('금괴장갑'),
('목걸이목걸이'),
('궤짝송곳니'),
('탄환비늘'),
('석상날개'),
('장갑창'),
('보물상자문양'),
('메달검'),
('머리띠갑옷'),
('쇠구슬심장'),
('쇠사슬'),
('깃털돌'),
('돌조각돌'),
('투척검심장'),
('포탄투구'),
('항아리심장'),
('투구결정'),
('방패창'),
('말발굽날개'),
('목걸이결정'),
('옷감'),
('동전'),
('철창방패'),
('단지투구'),
('상자핵'),
('반지망토'),
('포탄핵'),
('활대검'),
('망토망토'),
('버클결정'),
('철퇴부츠'),
('나침반조각'),
('지팡이갑옷'),
('철퇴문양'),
('열쇠장갑'),
('망치검'),
('동전부츠'),
('단검부츠'),
('활대비늘'),
('머리띠'),
('항아리발톱'),
('돌조각심장'),
('쇠구슬핵'),
('수정구창'),
('철문장갑'),
('날개결정'),
('깃털파편'),
('피리투구'),
('철편혼'),
('방탄복날개'),
('철문방패'),
('쇠구슬파편'),
('수정구핵'),
('화살돌'),
('방울비늘'),
('투척검투구'),
('검발톱'),
('갑주문양'),
('고리조각'),
('말발굽심장'),
('목걸이장갑'),
('투척검창'),
('뿔부츠'),
('룬발톱'),
('화살목걸이'),
('지팡이문양'),
('수리검투구'),
('보석창'),
('모자문양'),
('철편갑옷'),
('석궁파편'),
('상고리목걸이'),
('철퇴영혼'),
('메달장갑'),
('램프파편'),
('룬파편'),
('룬투구'),
('고리갑옷'),
('지팡이비늘'),
('깃발파편'),
('투척검날개'),
('뼈검'),
('포탄망토'),
('쇠구슬망토'),
('철문문양'),
('깃털발톱'),
('머리띠심장'),
('말발굽'),
('궤짝망토'),
('망치송곳니'),
('왕관문양'),
('단검장갑'),
('항아리문양'),
('발톱방패'),
('허리띠조각'),
('열쇠발톱'),
('방울목걸이'),
('방패망토'),
('모자심장'),
('상고리창'),
('투구문양'),
('뼈혼'),
('나침반영혼'),
('깃털영혼'),
('동전핵'),
('룬검'),
('허리띠투구'),
('은괴망토'),
('열쇠창'),
('가면망토'),
('투척검결정'),
('검창'),
('항아리송곳니'),
('방울문양'),
('뿔문양'),
('칼날검'),
('망치핵'),
('갑옷돌'),
('창망토'),
('갑옷혼'),
('단지날개'),
('장갑심장'),
('항아리창'),
('병조각'),
('검목걸이'),
('수리검심장'),
('상자'),
('모자돌'),
('항아리결정'),
('철창핵'),
('방패문양'),
('창날갑옷'),
('열쇠방패'),
('반지방패'),
('방패판비늘'),
('피리목걸이'),
('수리검방패'),
('왕관검'),
('팔찌장갑'),
('뼈갑옷'),
('반지반지'),
('훈장핵'),
('방탄복'),
('날개비늘'),
('조각상발톱'),
('날개창'),
('철문목걸이'),
('팔찌혼'),
('사슬갑옷'),
('송곳니검'),
('버클검'),
('머리띠목걸이'),
('지도창'),
('망토결정'),
('발톱비늘'),
('항아리핵'),
('뼈송곳니'),
('상자심장'),
('깃털투구'),
('투척검문양'),
('성배'),
('검부츠'),
('석판영혼'),
('인장문양'),
('병비늘'),
('검심장'),
('보석비늘'),
('장갑비늘'),
('말발굽망토'),
('철퇴창'),
('투구목걸이'),
('수정구망토'),
('팔찌송곳니'),
('보석파편'),
('뼈심장'),
('쇠사슬파편'),
('철창'),
('철퇴파편'),
('칼날발톱'),
('수리검반지'),
('활대조각'),
('포탄장갑'),
('훈장파편'),
('날개파편'),
('수정구부츠'),
('창핵'),
('용비늘갑옷'),
('버클방패'),
('머리띠창'),
('돌조각부츠'),
('망치비늘'),
('조각상투구'),
('모자투구'),
('가면창'),
('석판결정'),
('메달날개'),
('창날핵'),
('은괴부츠'),
('왕관영혼'),
('목걸이송곳니'),
('검결정'),
('팔찌결정'),
('석판조각'),
('망토반지'),
('철편송곳니'),
('방패심장'),
('지도비늘'),
('허리띠영혼'),
('쇠사슬핵'),
('용비늘심장'),
('뼈조각'),
('금괴투구'),
('장갑검'),
('방울투구'),
('쇠구슬갑옷'),
('방패돌'),
('왕관비늘'),
('수리검비늘'),
('마법서갑옷'),
('성배발톱'),
('창혼'),
('화살방패'),
('귀걸이투구'),
('단검파편'),
('열쇠검'),
('서적영혼'),
('수리검돌'),
('훈장혼'),
('버클투구'),
('궤짝문양'),
('부츠핵'),
('왕관부츠'),
('은괴비늘'),
('왕관조각'),
('망치발톱'),
('훈장검'),
('장갑송곳니'),
('모자갑옷'),
('철창문양'),
('철편부츠'),
('옷감장갑'),
('방탄복발톱'),
('방탄복조각'),
('화살결정'),
('모자송곳니'),
('검혼'),
('돌기둥방패'),
('반지영혼'),
('왕관발톱'),
('철편발톱'),
('인장심장'),
('단지검'),
('철문갑옷'),
('깃털날개'),
('병영혼'),
('금괴방패'),
('철문핵'),
('검방패'),
('철문조각'),
('보석투구'),
('반지발톱'),
('해골비늘'),
('귀걸이반지'),
('창결정'),
('석판목걸이'),
('망토영혼'),
('방탄복반지'),
('은괴갑옷'),
('돌조각창'),
('날개갑옷'),
('뼈목걸이'),
('쇠구슬발톱'),
('인장장갑'),
('석궁혼'),
('포탄비늘'),
('포탄반지'),
('보물상자돌'),
('뼈부츠'),
('검조각'),
('가면검'),
('쇠구슬검'),
('탄환날개'),
('발톱문양'),
('램프영혼'),
('인장파편'),
('발톱파편'),
('지도'),
('동전창'),
('항아리조각'),
('동전파편'),
('수리검핵'),
('깃발혼'),
('수리검혼'),
('금괴날개'),
('서적검'),
('갑옷심장'),
('돌기둥반지'),
('포탄파편'),
('램프부츠'),
('보물상자발톱'),
('동전반지'),
('머리띠망토'),
('훈장갑옷'),
('창날돌'),
('지팡이'),
('성배영혼'),
('깃털문양'),
('갑주목걸이'),
('부츠조각'),
('팔찌창'),
('부츠반지'),
('상고리갑옷'),
('인장발톱'),
('창살갑옷'),
('보물상자결정'),
('목걸이조각'),
('화살심장'),
('버클비늘'),
('비단돌'),
('칼날심장'),
('해골송곳니'),
('인장조각'),
('머리띠반지'),
('창반지'),
('뿔조각'),
('메달목걸이'),
('활대돌'),
('상자영혼'),
('장갑투구'),
('룬조각'),
('탄환결정'),
('반지비늘'),
('칼날비늘'),
('상고리파편'),
('석판투구'),
('나침반창'),
('수정구장갑'),
('철문날개'),
('비단날개'),
('석궁날개'),
('조각상검'),
('칼날날개'),
('해골망토'),
('뿔방패'),
('인장돌'),
('머리띠결정'),
('머리띠장갑'),
('피리혼'),
('철창날개'),
('검영혼'),
('고리비늘'),
('사슬부츠'),
('나침반부츠'),
('투구발톱'),
('쇠사슬송곳니'),
('검투구'),
('목걸이날개'),
('수정구'),
('지팡이장갑'),
('망치부츠'),
('단검송곳니'),
('날개돌'),
('창날송곳니'),
('창갑옷'),
('궤짝조각'),
('상자반지'),
('칼날갑옷'),
('망토날개'),
('창살결정'),
('룬송곳니'),
('마법서'),
('용비늘송곳니'),
('검망토'),
('램프'),
('탄환핵'),
('포탄목걸이'),
('열쇠비늘'),
('쇠구슬부츠'),
('탄환파편'),
('석상장갑'),
('깃털갑옷'),
('마법서발톱'),
('지도문양'),
('날개장갑');

-- 브랜드 데이터 삽입 (총 1000개)
INSERT INTO temp_brand (brand_name) VALUES
('HEMORRHOIDS'),
('Metoprolol Tartrate and Hydrochlorothiazide'),
('BEING WELL DIAPER RASH CREAMY'),
('Testosterone'),
('Acyclovir'),
('BuPROPion Hydrochloride'),
('Amoxicillin'),
('Kank-A'),
('Childrens Ibuprofen'),
('SBS 40'),
('Temazepam'),
('Loperamide Hydrochloride'),
('Alprazolam'),
('Gabapentin'),
('OXYGEN'),
('DIGESTION RELIEF'),
('Clarithromycin'),
('Shopko Diaper Rash Maximum Strength'),
('Bupivacaine Hydrochloride'),
('KLOR-CON M'),
('Clotrimazole'),
('FENTANYL CITRATE'),
('Clonidine Hydrochloride'),
('Spai-Sons'),
('Phenobarbital'),
('Anti-Bacterial Hand'),
('cooling'),
('Lorazepam'),
('Pamidronate Disodium'),
('Red Mulberry'),
('Magnesium Citrate'),
('Sufentanil Citrate'),
('Nu Skin Nu Colour'),
('Smart San Healthcare Personnel Handwash'),
('Privet'),
('VANIQA'),
('Fanapt'),
('Opahl'),
('FUCOIDAN ESSENCE'),
('Pfizerpen'),
('Lemon Drop Antibacterial Hand Wash'),
('DIANEAL Low Calcium with Dextrose'),
('DAYWEAR'),
('Ibuprofen'),
('Nicorette'),
('Pantoprazole Sodium'),
('Nu Skin Nu Colour'),
('Lorazepam'),
('Phenytoin'),
('MARCS'),
('METHYLPHENIDATE HYDROCHLORIDE'),
('Benzonatate'),
('Glipizide'),
('LOESTRIN Fe 1.5/30'),
('Ofloxacin'),
('MooreBrand Phenylephrine'),
('GUNA-ADDICT 1'),
('Escitalopram'),
('PENNSAID'),
('Se-Natal One'),
('UltraTag'),
('LOreal Paris Advanced Suncare Silky Sheer Face 30 Broad Spectrum SPF 30 Sunscreen'),
('Tri-Vit with Fluoride Drops'),
('Doxercalciferol'),
('Animal Hair and Dander Allergy Relief'),
('Body Satin'),
('Levothyroxine Sodium'),
('TREATMENT LIPSHINE'),
('Terazosin hydrochloride'),
('Hydrocortisone Acetate and Pramoxine Hydrochloride'),
('Thuja Occidentalis Kit Refill'),
('Crest Complete Multi-benefit'),
('Hydrocodone Bitartrate and Acetaminophen'),
('SIMVASTATIN'),
('Lansoprazole'),
('Betamethasone Dipropionate'),
('Levetiracetam'),
('BullFrog Water Armor Sport Super'),
('Allergena'),
('Heparin Sodium'),
('Citalopram'),
('Hydralazine Hydrochloride'),
('Cyclobenzaprine Hydrochloride'),
('Telmisartan'),
('Lorazepam'),
('Bayer'),
('GINGER'),
('Hydrochlorothiazide'),
('ZO SKIN HEALTH'),
('Diprivan'),
('Sonacaine Topical Anesthetic With Menthol'),
('Xylocaine'),
('health mart nicotine'),
('PREP AND PRIME BLEMISH CONTROL ACNE TREATMENT'),
('Cytogam'),
('Raspberry'),
('Nadolol'),
('CLOMIPRAMINE HYDROCHLORIDE'),
('CD DiorSnow UV Shield Pearly White - SPF50'),
('BAROX'),
('Marvel The Avengers Hand Sanitizer'),
('Pain Relief'),
('Regional Allergies Southern U.S.'),
('Methylphenidate Hydrochloride'),
('Risperidone'),
('allergy relief'),
('ADVIL'),
('Carbamazepine'),
('Tussin Original'),
('Oxymorphone Hydrochloride'),
('Family Wellness Maximum Strength Hydrocortisone'),
('fexofenadine hydrochloride'),
('Bayer'),
('LBEL Couleur Luxe Rouge Amplifier XP amplifying SPF 15'),
('Coppertone ultraGUARD Sunscreen'),
('GOLDENROD POLLEN'),
('Zohar Toothpaste'),
('Didanosine'),
('Cilostazol'),
('fondaparinux sodium'),
('Servo-Stat T'),
('Gelato APF'),
('Flawless Finish Bare Perfection Makeup SPF 8 Ivory'),
('Methazolamide'),
('Orange Scented Hand Sanitizer'),
('4 in 1 Pressed Mineral SPF 15 Golden Medium'),
('DOCTOR HOYS Arnica Boost'),
('Calcijex'),
('Leader Allerhist'),
('Cutiecaine'),
('Quality Choice Childrens Allergy Relief'),
('BC'),
('Vitamin A D'),
('FAMOTIDINE'),
('EarAche Therapy'),
('TRETIN.X'),
('Zolpidem Tartrate'),
('Dextroamphetamine Sulfate'),
('Midazolam Hydrochloride'),
('Lamivudine'),
('Ortho Tri Cyclen'),
('Primlev'),
('Metoprolol Tartate'),
('Gris-PEG'),
('Mirtazapine'),
('Naratriptan'),
('healthy accents sore throat'),
('Flunisolide'),
('Axe'),
('Sun Total Protector Color 30 Dark Tint'),
('CYZONE'),
('Labetalol Hydrochloride'),
('Fluconazole'),
('SMOKE-X'),
('CAPMIST'),
('Diltiazem Hydrochloride'),
('Oxycodone Hydrochloride'),
('Sugar Maple'),
('Lucky Super Soft'),
('LBEL REGRESSION JOUR Protective Complex With SPF 15 Facial Day Normal to Combination Skin'),
('Vitamin A and Vitamin D'),
('Rimmel London'),
('Mercurius Corr Kit Refill'),
('COUGH HP'),
('Povidone-Iodine'),
('Citalopram Hydrobromide'),
('Cefazolin'),
('Clindamycin Phosphate'),
('ADVAIR'),
('Burweed Marsh Elder'),
('12 hour nasal decongestant'),
('Red Maple'),
('OLUX'),
('BERRY BABY LIP BALM PEACH BERRY'),
('Parrot Head Dedicated to Sunshine Tan Enhancer 8'),
('LANEIGE SKIN VEIL'),
('Enteric Coated Aspirin'),
('Telmisartan and Hydrochlorothiazide'),
('HAND SANITIZER ALCOHOL FREE'),
('Methocarbamol'),
('Idarubicin Hydrochloride'),
('Regemarine'),
('Hydrochlorothiazide'),
('Fever - Infection'),
('Ibuprofen'),
('Genuine Aspirin'),
('SHISEIDO PERFECT REFINING FOUNDATION'),
('KLEENFOAM'),
('OXYGEN'),
('Phentermine Hydrochloride'),
('DawnMist Alcohol Hand Sanitizer'),
('TROSPIUM CHLORIDE'),
('Lyrica'),
('Cabergoline'),
('good sense milk of magnesia'),
('Quinapril'),
('Famotidine'),
('Furosemide'),
('Glyburide and Metformin Hydrochloride'),
('Childrens Allergy'),
('Povidone Iodine'),
('SunMark All Day Allergy'),
('ESIKA PERFECT SKIN COVERAGE CONCEALER SPF 17'),
('Sodium Polystyrene Sulfonate'),
('Clindamycin Hydrochloride'),
('Gentiana Absinthium'),
('Naproxen'),
('Cyclo/Mag 10mg/200mg'),
('Treatment Set TS329197'),
('Bronchial Cough Therapy'),
('LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25'),
('Mycophenolic Acid'),
('Fulton Street Market Ibuprofen'),
('SHISEIDO THE MAKEUP FOUNDATION'),
('FUSARIUM VASINFECTUM OXYSPORUM'),
('Amoxicillin'),
('Air'),
('Warfarin Sodium'),
('ACYCLOVIR'),
('Dexamethasone'),
('HYDRATING HEALING'),
('doxepin hydrochloride'),
('Vanilla cupcake anti-bacterial SCENTED HAND SANITIZER'),
('"levomefolate calcium, cyanocobalamin and pyridoxine hydrochloride"'),
('Nicorette'),
('BIONA-VIT'),
('Olbas Lozenges'),
('Adidas'),
('Caverject Impulse'),
('Professional Therapy'),
('BLUEBERRY'),
('Smart Sense Severe Cold and Flu NightTime'),
('Mapap'),
('diltiazem hydrochloride'),
('Hepar Sulphuris Calcareum 30c'),
('Metoprolol Tartrate'),
('Yao Shen Gao Pain Relieving Plaster'),
('Fluconazole'),
('Caffeine Citrate'),
('ASPERGILLUS FUMIGATUS'),
('ORGAN-I NR'),
('Canadian Blue Grass'),
('Horse Hair'),
('Sugared Pear Antibacterial Hand Sanitizer'),
('Methocarbamol'),
('allergy relief-d'),
('Solu-Medrol'),
('Biofreeze'),
('Arizona Cypress'),
('EPIFOAM'),
('Sulfamethoxazole and Trimethoprim'),
('Carnitor'),
('Aromafields Tiger Lily Scented Anti-Bacterial Hand'),
('Bio Glyoxal Phase'),
('Zemplar'),
('BANANA BOAT'),
('Galantamine'),
('Nicardipine Hydrochloride'),
('Naproxen'),
('leader omeprazole'),
('Topcare Childrens Ibuprofen'),
('Night Time Cherry'),
('NASACORT AQ'),
('Siladryl Allergy Medicine'),
('Treatment Set TS332147'),
('Bayberry'),
('H. Pylori'),
('Terrasil Cold Sore Treatment'),
('infants pain and fever'),
('PERCOCET'),
('Enalapril Maleate'),
('Glipizide and Metformin HCl'),
('lisinopril'),
('Benazepril Hydrochloride and Hydrochlorothiazide'),
('DG Body'),
('Bactoshield CHG'),
('Vital Male Sexual Energy'),
('Loperamide Hydrochloride'),
('Levetiracetam'),
('XtraCare Antibacterial Hand Cleanse'),
('Green MINT Mouth Rinse'),
('Oxycodone and Acetaminophen'),
('Goat Hair'),
('Haloperidol'),
('OXY Daily Moisturizer'),
('Promethazine Hydrochloride'),
('Xeloda'),
('Mountain Cedar'),
('Goats Milk'),
('Assured Instant Hand Sanitizer'),
('IASO FOR MEN WHITE EX AFTER SHAVE SUPREME'),
('Lisinopril'),
('Ibuprofen and Pseudoephedrine Hydrochloride'),
('Indomethacin'),
('COCOA BEAN'),
('SSD'),
('Cockroach American'),
('rx act ibuprofen pm'),
('Metformin Hydrochloride'),
('Olanzapine'),
('Levothyroxine Sodium'),
('Naproxen'),
('Boolicious Antibacterial Hand'),
('Wheat Bunt'),
('TAZICEF'),
('Anti Chafe Balm'),
('AVINZA'),
('Sani Professional Brand Sani-Hands'),
('Povidone-Iodine Pad'),
('Cough HP'),
('Azithromycin Dihydrate'),
('Midodrine Hydrochloride'),
('Medrol'),
('Daytime Nighttime'),
('Dexamethasone'),
('Clorazepate dipotassium'),
('SHISEIDO THE MAKEUP FOUNDATION'),
('Hemorrhoids'),
('Black Walnut'),
('Triamterene and Hydrochlorothiazide'),
('Depo-Medrol'),
('Equate NiteTime'),
('Dandruff'),
('NovoLog'),
('Buspirone Hydrochloride'),
('RITE AID CAPSICUM HOT'),
('Lisinopril'),
('Spironolactone'),
('ERY-TAB'),
('Stress Control'),
('CELEBREX'),
('Atenolol'),
('Isomers Sunscreen with UV pearls Broad Spectrm SPF 20'),
('Aller-Chord Food'),
('ORTHO GUARD'),
('Kinesys'),
('ESIKA'),
('KADIAN'),
('H-Balm Control'),
('Hydrocortisone Maximum Strength Plus 12 Moisturizers'),
('"Molds, Rusts and Smuts, Helminthosporium interseminatum"'),
('Instant Hand Sanitizer'),
('Moexipril Hydrochloride'),
('KLEENEX Antiseptic Hand Rub with Moisturizers'),
('Gabapentin'),
('Mentholatum'),
('Quetiapine fumarate'),
('CareAll Medicated Chest Rub'),
('Telmisartan'),
('Pandanus Calc. Carb'),
('California Black Walnut'),
('Enoxaparin Sodium'),
('Metoprolol Tartrate'),
('Amoxicillin and Clavulanate Potassium'),
('Anti-Bacterial Wipes'),
('ShopRite Infants Acetaminophen'),
('Hydroxyzine Hydrochloride'),
('Analgesic Creme Rub'),
('Salt Grass Pollen'),
('Acetaminophen and Codeine Phosphate'),
('Stressa Back and Neck Pain Relieving'),
('Solodyn'),
('Nicardipine Hydrochloride'),
('Clean and Clear Morning Glow Moisturizer'),
('Youduo Gentle Whitening Fluoride'),
('Lombardy Poplar'),
('SHISEIDO PURENESS MATIFYING COMPACT OIL-FREE (REFILL)'),
('Tiazac Extended Release'),
('Sal-Plant Gel'),
('Buprenorphine hydrochloride'),
('SENSAI CELLULAR PERFORMANCE CREAM FOUNDATION'),
('Hot Ice Soothing Analgesic Gel'),
('ALPRAZOLAM'),
('Pravastatin Sodium'),
('Peptic Relief'),
('Neutrogena Healthy Skin Compact Makeup'),
('CORZIDE'),
('Wal Zan 75'),
('Sandostatin LAR Depot'),
('Burweed Marsh Elder'),
('Hand Sanitizer'),
('Rat Epithelium'),
('Thiothixene'),
('VARIVAX'),
('Multi Flower'),
('Warfarin Sodium'),
('OXYGEN'),
('Tobramycin and Dexamethasone'),
('CLARINS Broad Spectrum SPF 15 Everlasting Foundation Tint 109'),
('Flecainide Acetate'),
('Warfarin Sodium'),
('Neomycin and Polymyxin B Sulfates and Hydrocortisone'),
('infants pain and fever'),
('PERFECTION LUMIERE'),
('Walgreen Anticavity Whitening'),
('SEROMYCIN'),
('Cocoa Latte Tinted Moisturizer Broad Spectrum SPF 25 Sunscreen Medium To Dark'),
('METHADONE HYDROCHLORIDE'),
('URSO'),
('Mane n Tail Daily Control Anti-Dandruff'),
('Disulfiram'),
('dg health cold and allergy'),
('ECHINACEA'),
('ANTIVENIN (MICRURUS FULVIUS)'),
('First Aid Original Bacitraycin Plus'),
('ACNE MEDICATION 5'),
('HYDROCODONE BITARTRATE AND ACETAMINOPHEN'),
('PROPRANOLOL HYDROCHLORIDE'),
('Anti-Bacterial Hand'),
('Galantamine'),
('Griseofulvin'),
('West Wheat Grass'),
('Levetiracetam'),
('House Dust'),
('Divas'),
('Warfarin Sodium'),
('Cefuroxime Axetil'),
('Clonazepam'),
('Hand Armor'),
('Levoxyl'),
('SBS 41'),
('DIGOX'),
('Venlafaxine Hydrochloride'),
('HYDROXYUREA'),
('SENEXON-S'),
('"Pollens - Trees, Oak, Red Quercus rubra"'),
('Metformin Hydrochloride'),
('Lycopodium Clavatum'),
('Nitrofurantoin (macrocrystals)'),
('Leader ClearLax'),
('up and up'),
('Hackberry'),
('Australian Gold'),
('Androgel'),
('Hand Sanitizer'),
('Leader Clear Lax'),
('Biaxin'),
('Medi First Plus Sinus Pain and Pressure'),
('Galantamine'),
('FENTANYL CITRATE'),
('Arizona Ash'),
('Sulfacetamide Sodium'),
('Sun Broad Spectrum SPF 30'),
('good neighbor pharmacy migraine relief'),
('Prednisone'),
('Furosemide'),
('Fluoxetine Hydrochloride'),
('ELIPHOS'),
('THE YEON LOTUS FLOWER BC CUSHION PACT'),
('valsartan and hydrochlorothiazide'),
('BackAid'),
('Varicose Veins'),
('Capecitabine'),
('Pleo Nig'),
('careone nighttime sleep aid'),
('Sinusitis Plus'),
('smart sense ibuprofen'),
('Homeopathic Acne'),
('Metformin Hydrochloride'),
('NICORETTE'),
('Pain Relieving Po Tong Oil'),
('equaline nighttime'),
('Esterified Estrogens and Methyltestosterone'),
('Allergy relief'),
('OvacePlus'),
('Kerasal PF-10'),
('Lamisil'),
('Constipation Symptom Formula'),
('Fluocinolone Acetonide'),
('Trazodone Hydrochloride'),
('Amlodipine Besylate and Benazepril Hydrochloride'),
('Burkhart'),
('Topical Anesthetic'),
('Simvastatin'),
('Chicken Feathers'),
('Lyrica'),
('Treatment Set TS344570'),
('Simvastatin'),
('CAREONE'),
('Etodolac'),
('Loratadine Allergy Relief'),
('good sense tussin cf'),
('Zhuanggu Shexiang Zhitonggao Pain Relieving Plaster'),
('NICOTINE TRANSDERMAL SYSTEM'),
('CVS PHARMACY'),
('Compro'),
('Loratadine'),
('X-PEL Anti-Lice'),
('COREGCR'),
('valsartan and hydrochlorothiazide'),
('FLOVENTHFA'),
('Head and Shoulders'),
('Escitalopram'),
('SkinCeuticals Sheer Physical UV Defense Broad Spectrum SPF 30 Sunscreen'),
('Ciprofloxacin'),
('Clonidine Hydrochloride'),
('GoodSense'),
('Olanzapine'),
('Ibuprofen'),
('ALLOPURINOL'),
('EPICOCCUM NIGRUM'),
('Diathesis'),
('Pseudoephedrine Hydrochloride'),
('Ibuprofen'),
('CARBON DIOXIDE'),
('Melvita PROSUN SPF 30 Sun'),
('Peptic Relief'),
('Stool Softener'),
('KINESYS'),
('Gabapentin'),
('Glyburide and Metformin Hydrochloride'),
('Bellagio Childrens Sunscreen SPF 45'),
('Povidone-Iodine'),
('Ropinirole Hydrochloride'),
('CELLBOOSTING HOMME SKIN'),
('Midazolam'),
('ED A-HIST'),
('Bupropion Hydrochloride'),
('Lotrel'),
('Hydroxyzine Hydrochloride'),
('Trelstar'),
('Venlafaxine Hydrochloride'),
('Valsartan and Hydrochlorothiazide'),
('Sulfamethoxazole and Trimethoprim'),
('Salicylic Acid'),
('Old Spice Red Zone Sweat Defense'),
('ANACARDIUM ORIENTALE'),
('Phentermine Hydrochloride'),
('PROcure Psoriapalm'),
('Claritin-D'),
('Polyethylene Glycol 3350'),
('Fluconazole'),
('Sinuforce'),
('Oxybutynin Chloride'),
('Oxytocin'),
('Cough and Cold'),
('Naproxen Sodium'),
('benazepril hydrochloride and hydrochlorothiazide'),
('Hand Cleanse'),
('Ibuprofen'),
('Clinical Strength MiracleDry Antiperspirant Deodorant AM'),
('ZALEPLON'),
('Foaming Hand Sanitizer'),
('Haemonetics Anticoagulant Citrate Dextrose Solution'),
('Hydrocodone bitartrate and ibuprofen'),
('Trial Antacid'),
('Clearasil Ultra'),
('All Day Allergy Relief'),
('Benazepril Hydrochloride'),
('Oxygen'),
('CeraVe'),
('VIIBRYD'),
('Garnier Nutritioniste Skin Renew'),
('VERELAN PM'),
('mupirocin'),
('Irbesartan'),
('SODIUM SULFACETAMIDE'),
('Albuterol Sulfate'),
('Glycopyrrolate'),
('Super Aqua Cleansing Oil'),
('Enalapril Maleate'),
('Clonazepam'),
('Ibuprofen'),
('Arbinoxa'),
('RESILIENCE LIFT'),
('Stool Softener'),
('Fluoxetine'),
('Diazepam'),
('Omeprazole'),
('potassium chloride'),
('AVERTEAX'),
('Conju Princess UV Sun Block'),
('Advanced Hand Sanitizer'),
('Umcka Cold Flu Orange'),
('Ropinirole Hydrochloride'),
('DERMA GRAN'),
('anna lotan PRO CC Color Control SPF25 Broad Spectrum Protection for All Skin Types'),
('Metoprolol Tartrate'),
('Bupropion Hydrochloride'),
('Eve Lom Brilliant Cover Concealer Broad Spectrum SPF 15 Sunscreen'),
('Loratadine'),
('PRESCRIPTIVES ALL SKINS MINERAL MAKEUP'),
('Prednisone'),
('Treatment Set TS331153'),
('Lisinopril and hydrochlorothiazide'),
('Nighttime Sleep Aid'),
('Safflower Seed'),
('Finacea'),
('allergy relief'),
('SunMark Allergy Relief'),
('100% Pure Green Tea Oil Free Moisturizer'),
('Haloperidol Decanoate'),
('PedvaxHIB'),
('H-Releve Hemorrhoidal'),
('Throar Dr.'),
('Good Sense Acid Reducer'),
('tizanidine hydrochloride'),
('"Standardized Grass Pollen, Sweet Vernal Grass"'),
('Lyrica'),
('pain relief'),
('LISINOPRIL AND HYDROCHLOROTHIAZIDE'),
('Amlodipine Besylate'),
('Sunbrellas Mineral Sunblock SPF 30'),
('Naphazoline'),
('allergy eye'),
('Myfortic'),
('Hemorrhoidal'),
('Haws Eyewash Additive'),
('Honey Vanilla Antibacterial Hand Wash'),
('sunmark nite time d'),
('Eplerenone'),
('sunmark Povidone-Iodine Topical'),
('Hydrocortisone'),
('Suphedrine'),
('Lamotrigine Extended Release'),
('Gentiana Absinthium'),
('Alprazolam'),
('AZITHROMYCIN'),
('Rexall Nicotine'),
('ATORVASTATIN CALCIUM'),
('Pomalyst'),
('Lucky Instant Hand Sanitizer Citrus Zest'),
('Citalopram Hydrobromide'),
('Rabeprazole Sodium'),
('Nitroglycerin'),
('PreviDent'),
('Pancuronium Bromide'),
('Sodium Chloride'),
('HYDROCODONE BITARTRATE AND ACETAMINOPHEN'),
('Nitrogen'),
('Dry Eye Therapy'),
('Fentanyl Citrate'),
('Adult Low strength Aspirin'),
('Amlodipine Besylate'),
('Natelle One'),
('Dr. Dream Hydramemory Deep Cleansing'),
('dg health infants pain and fever'),
('ZinClear SPF 30 Tinted'),
('sinus congestion and pain'),
('Clarins Broad Spectrum SPF 15 Sunscreen Care For Outdoor Sports'),
('Doxycycline Hyclate'),
('Amphotericin B'),
('HYPERPIGMENTATION TREATMENT'),
('Gold Bond Pain Relieving Foot Roll On'),
('Baclofen'),
('Morning Fresh'),
('Axe'),
('Allergy Relief'),
('Leader Acid Control'),
('Hy5'),
('temazepam'),
('Nobac Plus'),
('LV-FX'),
('English Plantain'),
('Ceftriaxone Sodium'),
('Healing'),
('Melphalan Hydrochloride'),
('SPORANOX'),
('Cefadroxil'),
('FACE IT RADIANCE POWDER PACT SPF25 MOISTURE VEIL NB17'),
('Carbamazepine (Chewable)'),
('Olive Vaginal Formula'),
('Benztropine Mesylate'),
('Albuterol Sulfate'),
('Diabetigen'),
('good sense ibuprofen cold and sinus'),
('Tramadol Hydrochloride'),
('Pork'),
('Cleocin'),
('Procainamide Hydrochloride'),
('smart sense flu and severe cold and cough'),
('Enoxaparin Sodium'),
('Vicodin'),
('American Beech'),
('Bug Bite'),
('Gillette Clinical Sport Advanced'),
('Ropinirole'),
('Motion Sickness'),
('RECOMBIVAX HB'),
('up and up acid reducer'),
('JIN GU WANG'),
('quinapril hydrochloride and hydrochlorothiazide'),
('Olanzapine'),
('ChemoClenz'),
('ClotrimazOil Antifungal'),
('CONDITION AND ENHANCE CLEAR'),
('Senna Laxative'),
('SERTRALINE HYDROCHLORIDE'),
('Heparin Sodium'),
('Simply Right Mucus Relief'),
('RUMEX ACETOSELLA POLLEN'),
('OxyContin'),
('OPANA'),
('BANANA BOAT'),
('Argentum Metallicum'),
('Horse Epithelia'),
('Latanoprost'),
('Ofloxacin'),
('NovoSeven'),
('Cuprum aceticum Zincum valerianicum'),
('Griseofulvin'),
('Ursodiol'),
('Ondansetron'),
('Clotrimazole'),
('amantadine hydrochloride'),
('Tamoxifen Citrate'),
('Fentanyl Citrate'),
('Sentravil PM-25'),
('ARTEMISIA FRIGIDA POLLEN'),
('Bupropion Hydrocloride'),
('up and up childrens acetaminophen'),
('ATORVASTATIN CALCIUM'),
('kids cold'),
('Therapeutic'),
('Antiacterial Hand Sanitizer'),
('Estradiol'),
('Hydrochlorothiazide'),
('Idole Skin Lightening'),
('LBEL FILLING EFFECT FOUNDATION SPF 10'),
('Clorpres'),
('TISSEEL'),
('Enalapril Maleate and Hydrochlorothiazide'),
('Shopko Antibacterial Foaming Hand Sanitizer'),
('Supreme'),
('ANTIBACTERIAL FOAMING HAND SP CUCUMBER AND MELON'),
('Promethazine Hydrochloride'),
('No7 Protect and Perfect Day Sunscreen Broad Spectrum SPF 15'),
('Muscle Rub'),
('up and up cold flu relief'),
('RED ORANGE SUN'),
('Glycopyrrolate'),
('Lisinopril'),
('Crinone'),
('Ceramide Lift and Firm Makeup Broad Spectrum Sunscreen SPF 15 Ecru'),
('Cromolyn Sodium'),
('Nascobal'),
('Indomethacin'),
('PERFORM'),
('rx act flu and sore throat'),
('VeraSeptine Multipurpose Moisture Barrier'),
('RK Detox'),
('Shopko Antibacterial Hand Sanitizer'),
('Scott'),
('ATORVASTATIN CALCIUM'),
('AQUAFRESH'),
('Indomethacin'),
('SohMed Acid Reducer'),
('Jade'),
('topcare cold'),
('Tizanidine Hydrochloride'),
('Water Oak'),
('up and up acetaminophen'),
('HYDROCODONE BITARTRATE AND ACETAMINOPHEN'),
('Alfenta'),
('Depo-Medrol'),
('Connectissue'),
('Golden Pear Antibacterial Foaming Hand Wash'),
('ACID GONE ANTACID'),
('Lidocaine Hydrochloride'),
('Multivitamin with fluoride'),
('Rose Sap Patch'),
('Sunflower Seed'),
('sodium chloride'),
('Levofloxacin'),
('Soothe and Cool Free'),
('Atropine Sulfate'),
('LABORATOIRE REMEDE TRANSLUCENT UV COAT TINT 0'),
('Clam'),
('Remedy Dimethicone Moisture Barrier'),
('healthy accents tussin dm'),
('RUE21 Cherry Antibacterial Hand Sanitizer'),
('PM Get Relief'),
('Instant Foaming Hand Sanitizer'),
('LETROZOLE'),
('Iman Time Control All Day Moisture Complex SPF 15'),
('Acyclovir'),
('Baclofen'),
('ASPIRIN'),
('Methimazole'),
('ESIKA 3-IN-1 PRO MAKE UP FOUNDATION SPF 20 BASE DE MAQUILLAJE PARA ROSTRO 3-EN-1 PRO FPS 20'),
('smooth lax'),
('Doxazosin'),
('Glyburide'),
('SUN CARE'),
('AMITRIPTYLINE HYDROCHLORIDE'),
('Instant Hand Sanitizer Green Apple Scented'),
('diltiazem hydrochloride'),
('FRESH JUICE E'),
('Zolmitriptan Orally Disintegrating'),
('Meloxicam'),
('Bisoprolol Fumarate and Hydrochlorothiazide'),
('Xylocaine'),
('LISINOPRIL AND HYDROCHLOROTHIAZIDE'),
('Cladosporium cladosporioides'),
('PREPOPIK'),
('Verapamil Hydrochloride'),
('CVS'),
('zaleplon'),
('Helium Oxygen Mix 80/20'),
('Trandolapril'),
('Gabapentin'),
('Chest Cold'),
('Natural Tan'),
('SHISEIDO URBAN ENVIRONMENT TINTED UV PROTECTOR'),
('Amoxicillin'),
('Midazolam hydrochloride'),
('Appeal Non-Alcohol Foaming Hand Sanitizer'),
('Everyday Clean'),
('Flu Relief Therapy Day Time'),
('Venlafaxine Hydrochloride'),
('Cyclogyl'),
('Acid Reducer'),
('Dexamethasone'),
('Loperamide Hydrochloride'),
('Fexofenadine hydrochloride'),
('healthy accents miconazole 3'),
('Cimetidine'),
('Bismutina'),
('Ondansetron'),
('Mulling Spices Antibacterial Foaming Hand Wash'),
('BETULA LENTA POLLEN'),
('ibuprofen'),
('Levothyroxine Sodium'),
('Morphine sulfate'),
('Topamax'),
('sunmark pain reliever'),
('Benazepril Hydrochloride'),
('PhysiciansCare Cold and Cough'),
('Sodium Chloride'),
('Formo Cresol'),
('Glycopyrrolate'),
('Nabumetone'),
('Sulwhasoo SNOWISE BRIGHTENING SERUM BB'),
('Apricot'),
('Personal Care Petroleum Jelly Skin Protectant'),
('Muro 128'),
('Equate Menthol extra strength'),
('Docusate Sodium'),
('Lipitor'),
('TEARS Naturale FORTE'),
('Enalapril Maleate and Hydrochlorothiazide'),
('Miconazole 3'),
('Meloxicam'),
('wet n wild'),
('BENICAR HCT'),
('Xeomin'),
('Mulberry'),
('supernatural airbrushed canvas broad spectrum spf 15 sunscreen'),
('ESSENTIAL SOLUTION HYALURONIC ACID MASK SHEET'),
('Rizatriptan'),
('Opana'),
('Esterified Estrogens and Methyltestosterone'),
('Metoprolol Tartrate'),
('Methocarbamol'),
('Transderm Scop'),
('Clindamycin hydrochloride'),
('VoSoL HC'),
('Dandruff'),
('True Natural broad sptectum spf 50'),
('CLINDAMYCIN HYDROCHLORIDE'),
('Risperidone'),
('Revonto'),
('Benzonatate'),
('Sulfur 6'),
('leader pain reliever'),
('Trihexyphenidyl Hydrochloride'),
('MIDODRINE HYDROCHLORIDE'),
('Softlips Tint'),
('Ribavirin'),
('Deferoxamine Mesylate'),
('Ethyl Rubbing Alcohol'),
('GUNA-DIZZY'),
('CELEBREX'),
('WhiskCare 375'),
('ROBINIA PSEUDOACACIA POLLEN'),
('Carteolol Hydrochloride'),
('Emtriva'),
('GNP Iodides Tincture'),
('Alendronate Sodium'),
('Softlips Sugar Plum Berry'),
('Triple Complex Digestion Tonic'),
('SUPRAX'),
('Nupercainal Bio-Active Hemorrhoidal'),
('Clarity Clear Skin Essentials'),
('Patricia Wexler Universal Anti-Aging Moisturizer with Sunscreen Broad Spectrum SPF 28'),
('Kids Disappearing Color SPF50 Broad Spectrum Suncreen Pink Strawberry Scented'),
('BLEMISH CORRECTING SERUM'),
('Mesna'),
('Chamomilla'),
('Doxycycline'),
('NIA 24 SPF 30'),
('Dry Idea Advanced Dry-Cotton Dry'),
('Escitalopram'),
('Tears Again'),
('HYVEE'),
('Fluconazole'),
('Dandruff'),
('Nite Time'),
('Geotrichum candidum'),
('napoleon PERDIS SHEER GENIUS LIQUID FOUNDATION BROAD SPECTRUM SPF 20 Look 6'),
('Bioelements'),
('Wal-Phed PE Non-Drying Sinus'),
('allergy relief'),
('ARNICA MONTANA'),
('Glyburide'),
('Buspirone Hydrochloride'),
('HAND SANITIZING'),
('equaline nighttime'),
('Brightening Hand Broad Spectrum SPF 20'),
('Ibuprofen and Pseudoephedrine Hydrochloride'),
('Prochlorperazine'),
('Allfen DM'),
('Glipizide'),
('CLINDAMYCIN PALMITATE HYDROCHLORIDE'),
('Vitamin A and Vitamin D'),
('Temovate'),
('Cetirizine Hydrochloride'),
('Aspirin'),
('simvastatin'),
('Banana Boat Sport SPF 60'),
('Night Time Cold/Flu Relief Original'),
('Olay Total Effects Feather Weight Moisturizer'),
('CD DIORSKIN NUDE SKIN-GLOWING MAKEUP SUNSCREEN BROAD SPECTRUM SPF 15 070 Dark Brown'),
('Iceberg Lettuce'),
('Speed Stick'),
('Topiramate'),
('WALGREENS ANTI ITCH'),
('Penicillin V Potassium'),
('Sorbitol'),
('FACIAL CLEANSER'),
('Ciprofloxacin'),
('ARSENICUM ALBUM'),
('"Pollens - Trees, Pine Mix"'),
('SODIUM CHLORIDE'),
('Protective Nail and skin'),
('Photocil'),
('Sodium Bicarbonate'),
('Diazepam'),
('Acetaminophen'),
('Garlic'),
('CENTER-AL - AMBROSIA ACANTHICARPA POLLEN'),
('Oxygen'),
('Sleep Aid'),
('Amoxicillin'),
('LBEL'),
('Acetaminophen and Codeine Phosphate'),
('Hand Cleanse'),
('MANGO BUTTER LIPSTICK'),
('doxycycline hyclate'),
('PredniSONE'),
('Good Neighbor Pharmacy Pain Relief'),
('Infla'),
('Bedside-Care'),
('Sertraline Hydrochloride'),
('Leader Infants Gas Relief'),
('LIP CONDITIONER'),
('Rembrandt Canker Sore'),
('Lidocaine Hydrochloride'),
('Vanilla Sugar Antibacterial Hand Sanitizer'),
('Folic Acid'),
('Tindamax'),
('Loratadine'),
('Facescreen'),
('Temazepam'),
('ALENDRONATE SODIUM'),
('Silent Nights'),
('Degree'),
('Perrigo Citalopram'),
('WHP Be gone Hay Fever'),
('ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)'),
('Antibacterial Hand -Vanilla Brown Sugar'),
('Recombinate'),
('gemcitabine'),
('Remedy Cleansing Body'),
('Careless Weed'),
('ACETAMINOPHEN PM'),
('Leader Arthritis Pain'),
('BENZTROPINE MESYLATE'),
('DIFFERIN'),
('HydrOXYzine Hydrochloride'),
('Furosemide'),
('Luminous Live Aura CC'),
('Red Kidney Beans'),
('Albuterol'),
('Neomycin and Polymyxin B Sulfates and Hydrocortisone'),
('CLE DE PEAU BEAUTE SILKY FOUNDATION I'),
('Ibuprofen'),
('Oil Control'),
('all day Allergy Relief D'),
('ATORVASTATIN CALCIUM'),
('Morphinum Muriaticum'),
('Leader Moisture SPF 15 Lip Balm'),
('Sheep Sorrel'),
('Rosmarinus Lavendula Special Order'),
('Paroxetine'),
('Pre Dental Visit'),
('"Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate and Amphetamine Sulfate"'),
('Metoclopramide'),
('Parsnip'),
('RINGERS');

-- 3. 기존 상품 테이블이 있다면 비우기
TRUNCATE TABLE product;

-- 4. 크로스 조인으로 상품 데이터 생성 (관형사 + 아이템만 조합)
-- 총 조합 가능한 상품 수: 900 × 1000 = 900000
-- 브랜드는 랜덤하게 할당
INSERT INTO product (name, brand_id, price, stock, likes, created_at, updated_at)
SELECT 
    CONCAT(d.determiner, ' ', i.item) as name,
    -- 브랜드는 1부터 1000 사이의 랜덤 값으로 할당
    FLOOR(1 + (RAND() * 1000)) as brand_id,
    -- 가격: 1000 ~ 1000000 사이의 랜덤 값
    FLOOR(1000 + (RAND() * 999000)) as price,
    -- 재고: 0 ~ 1000 사이의 랜덤 값
    FLOOR(RAND() * 1001) as stock,
    0 as likes,
    NOW() as created_at,
    NOW() as updated_at
FROM temp_determiner d
CROSS JOIN temp_item i
-- 브랜드는 크로스 조인하지 않고 랜덤 할당
LIMIT 900000;  -- 90만개 상품 생성

-- 5. 생성된 상품 수 확인
SELECT COUNT(*) as total_products FROM product;

-- 6. 샘플 데이터 확인
SELECT 
    p.id,
    p.name,
    b.brand_name,
    p.price,
    p.stock,
    p.likes
FROM product p
JOIN temp_brand b ON p.brand_id = b.id
LIMIT 20;

-- 7. 임시 테이블 정리
DROP TEMPORARY TABLE IF EXISTS temp_determiner;
DROP TEMPORARY TABLE IF EXISTS temp_item;
DROP TEMPORARY TABLE IF EXISTS temp_brand;

-- 8. 통계 정보
SELECT 
    '데이터 생성 완료' as status,
    900 as determiner_count,
    1000 as item_count,
    1000 as brand_count,
    900000 as total_combinations,
    (SELECT COUNT(*) FROM product) as actual_products;
